GalleryDemo/Controllers/PicController.cs
using Microsoft.AspNetCore.Mvc;

namespace GalleryDemo.Controllers;

public class PicController : Controller
{
    private readonly IWebHostEnvironment _webHostEnvironment;

    public PicController(IWebHostEnvironment webHostEnvironment)
    {
        _webHostEnvironment = webHostEnvironment;
    }

    [Route("api/pic/{**fileName}")]
    public IActionResult Get(string fileName)
    {
        var picPath = Path.Combine(_webHostEnvironment.ContentRootPath, "Pictures",fileName);
        var fileContent=System.IO.File.ReadAllBytes(picPath);
        return File(fileContent,"image/jpeg");
    }
}

GalleryDemo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace GalleryDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GalleryDemo/Pages/Gallery1.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GalleryDemo.Pages;

public class Gallery1Model : PageModel
{
    private readonly IWebHostEnvironment _webHostEnvironment;

    public Gallery1Model(IWebHostEnvironment webHostEnvironment)
    {
        _webHostEnvironment = webHostEnvironment;
    }

    public IList<string> FileList { get; set; }
    public void OnGet()
    {
        var picPath= Path.Combine(_webHostEnvironment.ContentRootPath,"Pictures");
        var files = Directory.GetFiles(picPath).ToList();
        FileList = new List<string>();
        foreach (var file in files)
        {
            FileList.Add(new FileInfo(file).Name);
        }
    }
}

GalleryDemo/Pages/Gallery2.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;

namespace GalleryDemo.Pages;

public class Gallery2Model : PageModel
{
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly IMemoryCache _memoryCache;
    public Gallery2Model(IWebHostEnvironment webHostEnvironment, IMemoryCache memoryCache)
    {
        _webHostEnvironment = webHostEnvironment;
        _memoryCache = memoryCache;
    }

    public IList<string> FileList { get; set; }
    public void OnGet()
    {
        if(_memoryCache.TryGetValue("pics",out IList<string> cachedPics) == false) { 

        var picPath = Path.Combine(_webHostEnvironment.ContentRootPath, "Pictures");
        var files = Directory.GetFiles(picPath).ToList();
        FileList = new List<string>();
        const string imageBase64 = "data:image/jpg;base64,";

        foreach (var file in files)
        {
            FileList.Add(imageBase64+Convert.ToBase64String(System.IO.File.ReadAllBytes(file)));
        }

            var cacheEntryOptions = new MemoryCacheEntryOptions()
              .SetSlidingExpiration(TimeSpan.FromSeconds(30));

            _memoryCache.Set("pics", FileList, cacheEntryOptions);
        }
        else
        {
            FileList = cachedPics;

        }
    }
}

GalleryDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GalleryDemo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

GalleryDemo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GalleryDemo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GalleryDemo/Pages/Gallery1.cshtml
@page
@model GalleryDemo.Pages.Gallery1Model
@{
}


@foreach (var file in Model.FileList){

    <img src="@Url.Action("Get","Pic",new { FileName=file})" style="max-height:200px"/>
}

GalleryDemo/Pages/Gallery2.cshtml
@page
@model GalleryDemo.Pages.Gallery2Model
@{
}

@foreach (var file in Model.FileList)
{

    <img src="@file" style="max-height:200px" />
}

GalleryDemo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GalleryDemo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GalleryDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GalleryDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">GalleryDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Gallery1">Multiple Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Gallery2">Base64 </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GalleryDemo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>